Repository wecode-bootcamp-korea/Wepicker-frontend, pull requests merged in 2021-01, with the labels that each got.

#7 [16기 구보현] Footer Layout 구현완료
  .eslintcache
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/images/Footer/wepicker_logo_white.png
  src/index.js
Labels: Status: Accepted

#1 [16기 이새봄] login 페이지 레이아웃 및 기능 구현 완료 (Footer Component 적용)
  .eslintcache
  src/Routes.js
  src/config.js
  src/images/imgData.js
  src/index.js
  src/pages/Agreement/Agreement.js
  src/pages/Agreement/Agreement.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/SignUp/SignUp.scss
  src/styles/common.scss
Labels: Status: 수정 요청

#3 [16기 이새봄] Agreement 레이아웃 구현 및 컴포넌트 추가 예정
  .eslintcache
  src/Routes.js
  src/pages/Agreement/Agreement.js
  src/pages/Agreement/Agreement.scss
  src/pages/Login/Login.scss
Labels: Status: 수정 요청, Status: 추가 기능 구현중

#8 [16기 이새봄] SignUp 페이지 레이아웃 및 기능 구현 완료 (Footer Component 적용)
  src/images/imgData.js
  src/pages/Agreement/Agreement.js
  src/pages/Agreement/Agreement.scss
  src/pages/Login/Login.scss
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: Status: 수정 요청

#6 [16기 구보현] Main Page 레이아웃, 기능 구현 완료 (컨플릭트 해결완료)
  .eslintcache
  .gitignore
  debug.log
  package-lock.json
  package.json
  src/Routes.js
  src/components/Footer/Footer.scss
  src/images/Main/beans.jpg
  src/images/Main/brush.jpg
  src/images/Main/coffeebeans.jpg
  src/images/Main/main01.jpg
  src/images/Main/office.jpg
  src/index.js
  src/pages/Agreement/Agreement.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: 리뷰 요청

#5 [16기 구보현] Nav Bar 레이아웃, 기능 구현 완료 (수정요청 사항 반영완료)
  .eslintcache
  .gitignore
  package-lock.json
  package.json
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/SideBar.js
  src/components/Nav/SideBar.scss
  src/images/Nav/cart.png
  src/images/Nav/heart.png
  src/images/Nav/human.png
  src/images/Nav/wepicker_logo.png
  src/index.js
  src/styles/common.scss
Labels: Status: 리뷰 요청

#11 [16기 구보현] Refactor: Nav Bar 링크 연결, 왼쪽 버튼 오류 해결
  .eslintcache
  src/Routes.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/SideBar.js
Labels: Status: 리뷰 요청

#10 [16기 구보현] Refactor: Footer / 컨플릭트 해결 완료
  .eslintcache
  package-lock.json
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: Status: Accepted

#12 [16기 구보현] Refactor: Main / 컨플릭트 해결 완료
  .eslintcache
  src/config.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: 리뷰 요청

#13 [16기 정민선] 상세페이지 장바구니 post 기능 구현중
  .eslintcache~d3c0cb186211042c314d945d50853c725b4d4f45
  debug.log
  package-lock.json
  src/pages/Shop/Components/ItemDetail/Components/ItemDesc/ItemDesc.js
  src/pages/Shop/Components/ItemDetail/Components/ItemDetailMenu/ItemDetailMenu.js
  src/pages/Shop/Components/ItemDetail/Components/ItemDetailPage/ItemDetailPage.js
  src/pages/Shop/Components/ItemDetail/Components/ItemDetailPage/ItemDetailPage.scss
  src/pages/Shop/Components/ItemDetail/ItemDetail.js
  src/pages/Shop/Shop.js
Labels: Status: 리뷰 요청

#14 [16기 정민선] 위시리스트 페이지 추가
  public/data/wishList.json
  src/Routes.js
  src/pages/Wish/Componenets/WishItem.js
  src/pages/Wish/Componenets/WishItem.scss
  src/pages/Wish/WishList.js
  src/pages/Wish/WishList.scss
Labels: Status: 리뷰 요청

#9 [16기 구보현] Shoping Cart Page 레이아웃, 기능 구현 완료
  .eslintcache~main
  public/data/selectCartItemData.json
  src/Routes.js
  src/images/Cart/AddwishHeart.png
  src/pages/Cart/CartItemList.js
  src/pages/Cart/CartItemList.scss
  src/pages/Cart/CartPage.js
  src/pages/Cart/CartPage.scss
Labels: Status: 수정 요청

#15 [16기 구보현] Add: 네브바 위시리스트 페이지 추가버전 신규 브랜치 생성 / 카트 머지 시 카트 페이지 추가 예정
  src/components/Nav/Nav.js
  src/components/Nav/SideBar.js
Labels: Status: 리뷰 요청
